---
extends: eslint:recommended

parserOptions:
  sourceType: module

rules:
  semi:
    - error
    - never
  no-extra-semi: 2
  no-tabs: error
  no-unused-vars: warn
  no-console: off

globals:
  AFRAME: true
  THREE: true
  $id: true
  $: true

env:
  es6: true
  browser: true
